# Then add these aliases:
alias sp-init='supabase init'
alias sp-login='supabase login'
alias sp-link-env='source .env && echo "linking to $SUPABASE_PROJECT_ID ... using password=$SUPABASE_PROJECT_PASSWORD" && supabase link --project-ref $SUPABASE_PROJECT_ID'
alias sp-gen-types='source .env && supabase gen types --lang=typescript --project-id "$SUPABASE_PROJECT_ID" --schema public > src/types/database.types.ts'
alias sp-db-mnew='supabase migration new $1'
alias sp-db-mup='supabase migration up --linked'
alias sp-db-reset='supabase db reset --linked'
alias sp-db-seed='node --env-file=.env database/sedding.js'
alias sp-db-rs='sp-db-reset && node --env-file=.env database/sedding.js'
alias node-env-debug='source .env && node -e "console.log(true)"'
alias debug-alias='/usr/bin/echo "test"'